import React from 'react';
import DarkModeProvider from "./_contexts/DarkModeProvider";
import './globals.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}): React.JSX.Element {

    return (
        <html lang="en">
            <body>
                <DarkModeProvider>
                    <div className="flex flex-col" id="layout" data-testid="layout">
                        <main>
                            { children }
                        </main>
                    </div>
                </DarkModeProvider>
            </body>
        </html>
    );
}
